### ISSUE TITLE
Query about the noise level and privacy level

### ISSUE THREAD

**Issue by XTxiatong** [visitworld123/FedFed#2]
Thanks for the code. May I ask why two noise levels are added to the shared features, i.e., VAE_std1: 0.2. VAE_std2: 0.25? How is this correspnding to the paper?

**Comment by XTxiatong** [comment]
Could you also explain a bit more about how Figure 2(c) and Figure 16 are generated? How do you estimate privacy level  \varepsilon from the noise std?

**Comment by visitworld123** [comment]
Thanks for your interest in our work! 
For the first problem, we add a more safety noise like VAE_std2: 0.25 for better performance, you also can use only one noise. How much noise to add and how much data to share depends on the tradeoff between communication overhead and performance
Secondly,  we adjust $\sigma_e$'s value , with the relation $\varepsilon =\Delta f \sqrt{\ln(1/\delta)/ \sigma_e}$, When the  $\sigma_e^2$=0.15, the $\varepsilon = 1\times\sqrt{\ln(1/10^{-3})/ \sqrt{0.15}}=4.22$. $\Delta f$ and $\delta$ are constant.
I hope my answer solves your problem. Have a nice day!
